# Generated by Django 3.0.8 on 2020-07-22 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200702_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('user', 'movie')},
        ),
    ]
